name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.10.0
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.9.1 <2.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player:
    git:
      url: https://github.com/recastrodiaz/plugins.git
      path: packages/video_player/video_player
      ref: develop2
  wakelock: ">=0.1.2 <0.2.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
